spring.application.name=personal-task-decision-mcp-server
#server.port=808
server.port=${PORT:8080}

#management.endpoints.web.exposure.include=health,info

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

mcp.api.key=${MCP_API_KEY}


mcp.server.name=personal-task-decision-mcp
mcp.server.version=1.0.0
mcp.server.description=Task prioritization and decision MCP server