spring.application.name=personal-task-decision-mcp-server
#server.port=808
server.port=${PORT:8080}

#management.endpoints.web.exposure.include=health,info

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

mcp.api.key=mcp_secret_key#savera_paro_sawaal