spring.application.name=personal-task-decision-mcp-server
#server.port=808
server.port=${PORT:8080}

spring.ai.mcp.server.name=personal-task-decision-mcp
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.annotation-scanner.enabled=true
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

#management.endpoints.web.exposure.include=health,info

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

mcp.api.key=${MCP_API_KEY:mcp_server_key_dev_key}


#mcp.server.name=personal-task-decision-mcp
#mcp.server.version=1.0.0
#mcp.server.description=Task prioritization and decision MCP server


#spring.main.banner-mode=off